import React, { useState } from 'react';
import { RoomScan, Suggestion } from '../types';
import {
  Layers,
  Sparkles,
  CheckCircle2,
  Circle,
  Clock,
  ArrowRight,
  Maximize2,
  Upload,
  Download,
  Eye,
  ListTodo,
  TrendingDown,
  Info,
  Loader2,
  Share2,
  RefreshCw
} from 'lucide-react';

interface WorkspaceViewProps {
  scan: RoomScan;
  onNewScanClick: () => void;
  onUpdateScan: (updatedScan: RoomScan) => void;
  onGenerateVisionRender: (scan: RoomScan) => Promise<void>;
  isGeneratingVision: boolean;
}

export const WorkspaceView: React.FC<WorkspaceViewProps> = ({
  scan,
  onNewScanClick,
  onUpdateScan,
  onGenerateVisionRender,
  isGeneratingVision,
}) => {
  const [activeTab, setActiveTab] = useState<'hotspots' | 'vision' | 'checklist'>('hotspots');
  const [selectedSuggestionId, setSelectedSuggestionId] = useState<string | null>(
    scan.suggestions[0]?.id || null
  );

  const toggleSuggestionComplete = (id: string) => {
    const updatedSuggestions = scan.suggestions.map((s) =>
      s.id === id ? { ...s, completed: !s.completed } : s
    );
    onUpdateScan({ ...scan, suggestions: updatedSuggestions });
  };

  const toggleStepComplete = (stepNumber: number) => {
    const updatedSteps = scan.declutterSteps.map((step) =>
      step.stepNumber === stepNumber ? { ...step, completed: !step.completed } : step
    );
    onUpdateScan({ ...scan, declutterSteps: updatedSteps });
  };

  const completedSuggestionsCount = scan.suggestions.filter((s) => s.completed).length;
  const completedStepsCount = scan.declutterSteps.filter((s) => s.completed).length;

  const totalNoiseReduction = scan.suggestions.reduce(
    (acc, s) => (s.completed ? acc + s.visualNoiseReductionPct : acc),
    0
  );

  const totalTimeEstimateMinutes = scan.suggestions.reduce(
    (acc, s) => acc + s.timeEstimateMinutes,
    0
  );

  const exportPlanAsMarkdown = () => {
    const md = `# CLUTTERLESS — DECLUTTERING REPORT
Room: ${scan.roomName} (${scan.roomType})
Date: ${scan.timestamp}
Clutter Volume Score: ${scan.clutterVolumeScore}% | Target Shift: ${scan.atmosphericShift}

## Spatial Summary
${scan.summary}

## Object Groups Breakdown
${scan.objectGroups
  .map(
    (g) =>
      `- **${g.category}** (~${g.itemCountEstimate} items | Impact: ${g.impact}): ${g.recommendedAction}`
  )
  .join('\n')}

## Recommended Action Plan
${scan.suggestions
  .map(
    (s, idx) =>
      `${idx + 1}. [${s.completed ? 'x' : ' '}] **${s.title}** (${s.zoneTag} | ~${s.timeEstimateMinutes}m): ${s.description}`
  )
  .join('\n')}

## Step-by-Step Checklist
${scan.declutterSteps
  .map(
    (st) =>
      `- [${st.completed ? 'x' : ' '}] Step ${st.stepNumber}: ${st.title} (~${st.estimatedMinutes}m)\n  ${st.detail}`
  )
  .join('\n')}

---
Generated by Clutterless Studio Intelligence
`;

    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `clutterless-plan-${scan.roomName.toLowerCase().replace(/\s+/g, '-')}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex-1 flex flex-col lg:flex-row overflow-y-auto lg:overflow-hidden bg-[#FDFCFB]">
      {/* LEFT SIDEBAR: Active Session & Metrics */}
      <section className="w-full lg:w-[440px] border-b lg:border-b-0 lg:border-r border-black p-6 md:p-10 flex flex-col justify-between shrink-0 bg-[#FDFCFB]">
        <div className="space-y-8">
          <div>
            <div className="flex items-center justify-between mb-4">
              <p className="font-mono-code text-[10px] opacity-60 uppercase tracking-[0.3em]">
                Active Session — 01
              </p>
              <span className="bg-black text-white px-2 py-0.5 font-mono-code text-[9px] uppercase tracking-widest">
                {scan.roomType}
              </span>
            </div>

            <h1 className="text-5xl md:text-6xl font-bold leading-[0.9] tracking-tighter uppercase mb-4 font-editorial">
              {scan.roomName}
            </h1>

            <p className="text-base leading-snug opacity-80 max-w-[340px]">
              {scan.summary}
            </p>
          </div>

          {/* Metric Grid */}
          <div className="grid grid-cols-2 gap-3">
            <div className="border border-black p-4 flex flex-col justify-between bg-white shadow-[4px_4px_0px_#1A1A1A]">
              <span className="font-mono-code text-[9px] uppercase opacity-60">
                Volume Score
              </span>
              <div className="flex items-baseline gap-1 mt-2">
                <span className="text-4xl font-bold font-serif-italic tracking-tighter">
                  {scan.clutterVolumeScore}%
                </span>
                <span className="text-[10px] font-mono-code text-[#FF5F00]">
                  {scan.clutterVolumeScore > 60 ? 'HIGH NOISE' : 'SERENE'}
                </span>
              </div>
            </div>

            <div className="border border-black p-4 flex flex-col justify-between bg-white shadow-[4px_4px_0px_#1A1A1A]">
              <span className="font-mono-code text-[9px] uppercase opacity-60">
                Efficiency Index
              </span>
              <div className="flex items-baseline gap-1 mt-2">
                <span className="text-4xl font-bold font-serif-italic tracking-tighter text-[#FF5F00]">
                  {scan.efficiencyIndex}
                </span>
                <span className="text-[10px] font-mono-code opacity-50">PTS</span>
              </div>
            </div>
          </div>

          {/* Object Groups List */}
          <div className="border border-black p-4 bg-white">
            <div className="flex items-center justify-between mb-3 border-b border-black/20 pb-2">
              <span className="font-mono-code text-[10px] uppercase font-bold tracking-widest">
                Identified Object Clusters
              </span>
              <span className="font-mono-code text-[9px] uppercase bg-black text-white px-1.5 py-0.5">
                {scan.objectGroups.length} Groups
              </span>
            </div>

            <div className="space-y-3 max-h-48 overflow-y-auto pr-1">
              {scan.objectGroups.map((group, idx) => (
                <div key={idx} className="border-b border-black/10 pb-2 last:border-0">
                  <div className="flex items-center justify-between">
                    <span className="font-mono-code text-xs font-bold truncate max-w-[200px]">
                      {group.category}
                    </span>
                    <span
                      className={`text-[9px] font-mono-code uppercase px-1.5 py-0.5 font-bold ${
                        group.impact === 'High'
                          ? 'bg-[#FF5F00] text-white'
                          : group.impact === 'Medium'
                          ? 'bg-black text-white'
                          : 'bg-neutral-200 text-black'
                      }`}
                    >
                      ~{group.itemCountEstimate} items
                    </span>
                  </div>
                  <p className="text-[11px] opacity-70 mt-0.5 leading-tight">
                    {group.recommendedAction}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Drag/Drop Replace File Trigger */}
        <div
          onClick={onNewScanClick}
          className="mt-6 border-2 border-black border-dashed h-28 flex flex-col items-center justify-center text-center cursor-pointer hover:bg-black hover:text-white transition-colors duration-200 group bg-white"
        >
          <span className="font-mono-code text-[10px] uppercase mb-2 tracking-widest group-hover:text-white">
            Upload new photo to scan
          </span>
          <div className="w-8 h-8 border border-current rounded-full flex items-center justify-center font-mono-code text-lg">
            +
          </div>
        </div>
      </section>

      {/* RIGHT MAIN STAGE: Image Viewer, Hotspots, AI Vision, Steps */}
      <section className="flex-1 bg-[#F0EFED] p-4 md:p-8 relative flex flex-col justify-between overflow-hidden">
        {/* Top View Mode Navigation */}
        <div className="flex flex-wrap items-center justify-between gap-3 mb-4">
          <div className="flex items-center gap-1 bg-white border border-black p-1 shadow-[4px_4px_0px_#1A1A1A]">
            <button
              onClick={() => setActiveTab('hotspots')}
              className={`px-4 py-2 text-[10px] font-mono-code uppercase tracking-widest font-bold transition-all flex items-center gap-1.5 ${
                activeTab === 'hotspots'
                  ? 'bg-black text-white'
                  : 'text-black hover:bg-neutral-100'
              }`}
            >
              <Eye className="w-3.5 h-3.5" />
              <span>Spatial Overlay</span>
            </button>

            <button
              onClick={() => setActiveTab('vision')}
              className={`px-4 py-2 text-[10px] font-mono-code uppercase tracking-widest font-bold transition-all flex items-center gap-1.5 ${
                activeTab === 'vision'
                  ? 'bg-black text-white'
                  : 'text-black hover:bg-neutral-100'
              }`}
            >
              <Sparkles className="w-3.5 h-3.5 text-[#FF5F00]" />
              <span>AI Decluttered Vision</span>
            </button>

            <button
              onClick={() => setActiveTab('checklist')}
              className={`px-4 py-2 text-[10px] font-mono-code uppercase tracking-widest font-bold transition-all flex items-center gap-1.5 ${
                activeTab === 'checklist'
                  ? 'bg-black text-white'
                  : 'text-black hover:bg-neutral-100'
              }`}
            >
              <ListTodo className="w-3.5 h-3.5" />
              <span>Action Steps ({completedStepsCount}/{scan.declutterSteps.length})</span>
            </button>
          </div>

          <div className="flex items-center gap-2">
            <span className="font-mono-code text-[10px] uppercase opacity-60">
              Noise Reduction Progress:
            </span>
            <span className="font-mono-code text-xs font-bold bg-black text-[#FF5F00] px-2 py-1">
              -{totalNoiseReduction}% Reduced
            </span>
          </div>
        </div>

        {/* MAIN STAGE CONTENT */}
        <div className="flex-1 border border-black relative overflow-hidden bg-white shadow-[12px_12px_0px_rgba(0,0,0,0.06)] min-h-[420px] flex flex-col">
          {activeTab === 'hotspots' && (
            <div className="relative w-full h-full flex-1 flex flex-col lg:flex-row overflow-hidden">
              {/* Image Canvas with Hotspot Pins */}
              <div className="relative flex-1 bg-neutral-900 flex items-center justify-center min-h-[300px] overflow-hidden">
                <div className="absolute top-4 left-4 bg-black text-white px-2.5 py-1 text-[9px] font-mono-code uppercase tracking-widest z-10 border border-white/20">
                  Current State
                </div>

                <img
                  src={scan.imageUrl}
                  alt={scan.roomName}
                  className="w-full h-full object-contain max-h-[650px]"
                />

                {/* Hotspot Pins Overlay */}
                {scan.suggestions.map((sug, index) => {
                  const isSelected = selectedSuggestionId === sug.id;
                  const xPct = Math.max(10, Math.min(90, sug.targetCoordinates?.x || 50));
                  const yPct = Math.max(10, Math.min(90, sug.targetCoordinates?.y || 50));

                  return (
                    <button
                      key={sug.id}
                      onClick={() => setSelectedSuggestionId(sug.id)}
                      style={{ left: `${xPct}%`, top: `${yPct}%` }}
                      className={`absolute -translate-x-1/2 -translate-y-1/2 group transition-all z-20 ${
                        isSelected ? 'scale-125 z-30' : 'hover:scale-110'
                      }`}
                    >
                      <div
                        className={`w-8 h-8 rounded-full border-2 flex items-center justify-center font-mono-code text-xs font-bold transition-all shadow-lg ${
                          sug.completed
                            ? 'bg-emerald-600 border-white text-white'
                            : isSelected
                            ? 'bg-[#FF5F00] border-black text-white ring-4 ring-[#FF5F00]/40'
                            : 'bg-black border-white text-white hover:bg-[#FF5F00]'
                        }`}
                      >
                        #{index + 1}
                      </div>

                      {/* Tooltip Tag on hover */}
                      <div className="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 hidden group-hover:block bg-black text-white text-[9px] font-mono-code uppercase tracking-widest px-2 py-1 whitespace-nowrap z-40 border border-white/20 shadow-md">
                        {sug.zoneTag}
                      </div>
                    </button>
                  );
                })}
              </div>

              {/* Suggestions Side Drawer */}
              <div className="w-full lg:w-96 border-t lg:border-t-0 lg:border-l border-black bg-[#FDFCFB] p-4 md:p-6 overflow-y-auto max-h-[650px] space-y-4">
                <div className="flex items-center justify-between border-b border-black/20 pb-2">
                  <span className="font-mono-code text-[10px] uppercase font-bold tracking-widest">
                    AI Spatial Suggestions ({completedSuggestionsCount}/{scan.suggestions.length})
                  </span>
                  <span className="font-mono-code text-[9px] uppercase text-[#FF5F00]">
                    ~{totalTimeEstimateMinutes}m Total
                  </span>
                </div>

                <div className="space-y-4">
                  {scan.suggestions.map((sug, index) => {
                    const isSelected = selectedSuggestionId === sug.id;
                    return (
                      <div
                        key={sug.id}
                        onClick={() => setSelectedSuggestionId(sug.id)}
                        className={`border p-4 cursor-pointer transition-all ${
                          isSelected
                            ? 'border-2 border-black bg-white shadow-[6px_6px_0px_#FF5F00]'
                            : sug.completed
                            ? 'border-neutral-300 bg-neutral-100 opacity-60'
                            : 'border-black bg-white hover:border-[#FF5F00]'
                        }`}
                      >
                        <div className="flex items-start justify-between gap-2 mb-2">
                          <div className="flex items-center gap-2">
                            <span className="bg-black text-white text-[9px] font-mono-code px-1.5 py-0.5 uppercase font-bold">
                              #{index + 1}
                            </span>
                            <span className="font-mono-code text-[9px] uppercase text-[#FF5F00] font-bold">
                              {sug.zoneTag}
                            </span>
                          </div>

                          <button
                            onClick={(e) => {
                              e.stopPropagation();
                              toggleSuggestionComplete(sug.id);
                            }}
                            className="p-1 hover:text-[#FF5F00]"
                          >
                            {sug.completed ? (
                              <CheckCircle2 className="w-5 h-5 text-emerald-600" />
                            ) : (
                              <Circle className="w-5 h-5 text-neutral-400" />
                            )}
                          </button>
                        </div>

                        <h3 className="text-sm font-bold uppercase leading-tight font-editorial mb-2">
                          {sug.title}
                        </h3>

                        <p className="text-xs opacity-80 leading-relaxed mb-3">
                          {sug.description}
                        </p>

                        <div className="flex items-center justify-between font-mono-code text-[9px] uppercase opacity-70 border-t border-black/10 pt-2">
                          <span className="flex items-center gap-1">
                            <Clock className="w-3 h-3 text-[#FF5F00]" />
                            {sug.timeEstimateMinutes} mins
                          </span>
                          <span className="font-bold text-black">
                            -{sug.visualNoiseReductionPct}% Noise
                          </span>
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            </div>
          )}

          {activeTab === 'vision' && (
            <div className="relative w-full h-full flex-1 flex flex-col p-6 overflow-y-auto">
              <div className="flex items-center justify-between mb-4 border-b border-black pb-3">
                <div>
                  <p className="font-mono-code text-[10px] uppercase text-[#FF5F00] font-bold">
                    AI Proposed Vision
                  </p>
                  <h3 className="text-2xl font-bold uppercase font-editorial">
                    Architectural Reorganization Render
                  </h3>
                </div>

                <button
                  onClick={() => onGenerateVisionRender(scan)}
                  disabled={isGeneratingVision}
                  className="bg-black text-white px-5 py-2.5 font-mono-code text-[10px] uppercase tracking-widest font-bold flex items-center gap-2 hover:bg-[#FF5F00] transition-colors shadow-[3px_3px_0px_#1A1A1A] disabled:opacity-50"
                >
                  {isGeneratingVision ? (
                    <>
                      <Loader2 className="w-3.5 h-3.5 animate-spin text-[#FF5F00]" />
                      <span>Generating Render...</span>
                    </>
                  ) : (
                    <>
                      <Sparkles className="w-3.5 h-3.5 text-[#FF5F00]" />
                      <span>{scan.aiVisionImageUrl ? 'Regenerate Render' : 'Generate AI Render'}</span>
                    </>
                  )}
                </button>
              </div>

              {scan.aiVisionImageUrl ? (
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6 flex-1 items-center">
                  <div className="border border-black bg-neutral-900 p-2 shadow-[6px_6px_0px_#1A1A1A] flex flex-col">
                    <span className="bg-black text-white px-2 py-1 text-[9px] font-mono-code uppercase w-max mb-2">
                      Original State
                    </span>
                    <img
                      src={scan.imageUrl}
                      alt="Original"
                      className="w-full h-64 md:h-80 object-cover border border-white/20"
                    />
                  </div>

                  <div className="border border-black bg-neutral-900 p-2 shadow-[6px_6px_0px_#FF5F00] flex flex-col">
                    <span className="bg-[#FF5F00] text-white px-2 py-1 text-[9px] font-mono-code uppercase w-max mb-2 font-bold">
                      AI Decluttered Vision
                    </span>
                    <img
                      src={scan.aiVisionImageUrl}
                      alt="AI Vision"
                      className="w-full h-64 md:h-80 object-cover border border-white/20"
                    />
                  </div>
                </div>
              ) : (
                <div className="flex-1 border-2 border-dashed border-black bg-[#F0EFED] p-8 flex flex-col items-center justify-center text-center space-y-4 my-auto">
                  <div className="w-14 h-14 rounded-full border border-black flex items-center justify-center bg-white shadow-[4px_4px_0px_#1A1A1A]">
                    <Sparkles className="w-6 h-6 text-[#FF5F00]" />
                  </div>

                  <div className="max-w-md">
                    <h4 className="font-bold text-lg uppercase font-editorial mb-1">
                      Ready to Preview Your Decluttered Space?
                    </h4>
                    <p className="text-xs opacity-70 mb-4">
                      {scan.visionConceptPrompt}
                    </p>
                  </div>

                  <button
                    onClick={() => onGenerateVisionRender(scan)}
                    disabled={isGeneratingVision}
                    className="bg-black text-white px-8 py-3 text-[11px] font-mono-code uppercase tracking-widest font-bold hover:bg-[#FF5F00] transition-colors shadow-[4px_4px_0px_#1A1A1A] flex items-center gap-2"
                  >
                    {isGeneratingVision ? (
                      <>
                        <Loader2 className="w-4 h-4 animate-spin text-[#FF5F00]" />
                        <span>Rendering Architectural Model...</span>
                      </>
                    ) : (
                      <>
                        <Sparkles className="w-4 h-4 text-[#FF5F00]" />
                        <span>Generate AI Vision Render Now</span>
                      </>
                    )}
                  </button>
                </div>
              )}
            </div>
          )}

          {activeTab === 'checklist' && (
            <div className="relative w-full h-full flex-1 flex flex-col p-6 overflow-y-auto">
              <div className="flex items-center justify-between mb-4 border-b border-black pb-3">
                <div>
                  <p className="font-mono-code text-[10px] uppercase text-[#FF5F00] font-bold">
                    Systematic Declutter Sequence
                  </p>
                  <h3 className="text-2xl font-bold uppercase font-editorial">
                    Step-by-Step Execution Plan
                  </h3>
                </div>

                <div className="flex items-center gap-3">
                  <span className="font-mono-code text-xs">
                    {completedStepsCount} of {scan.declutterSteps.length} Steps Complete
                  </span>
                </div>
              </div>

              <div className="space-y-3 flex-1">
                {scan.declutterSteps.map((step) => (
                  <div
                    key={step.stepNumber}
                    onClick={() => toggleStepComplete(step.stepNumber)}
                    className={`border p-4 cursor-pointer transition-all flex items-start gap-4 ${
                      step.completed
                        ? 'border-neutral-300 bg-neutral-100 opacity-60'
                        : 'border-black bg-white hover:border-[#FF5F00] shadow-[4px_4px_0px_#1A1A1A]'
                    }`}
                  >
                    <button className="mt-0.5 text-black hover:text-[#FF5F00]">
                      {step.completed ? (
                        <CheckCircle2 className="w-6 h-6 text-emerald-600" />
                      ) : (
                        <Circle className="w-6 h-6 text-neutral-400" />
                      )}
                    </button>

                    <div className="flex-1">
                      <div className="flex items-center justify-between gap-2 mb-1">
                        <span className="font-mono-code text-xs font-bold uppercase tracking-wider">
                          Step 0{step.stepNumber}: {step.title}
                        </span>
                        <span className="font-mono-code text-[9px] uppercase bg-black text-white px-2 py-0.5">
                          ~{step.estimatedMinutes} Mins
                        </span>
                      </div>
                      <p className="text-xs opacity-80 leading-relaxed">
                        {step.detail}
                      </p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* BOTTOM METRICS & ACTIONS FOOTER */}
        <div className="mt-6 flex flex-col sm:flex-row items-center justify-between gap-4 pt-2">
          <div className="flex flex-wrap items-center gap-6 md:gap-12 text-left">
            <div className="flex flex-col">
              <span className="font-mono-code text-[9px] uppercase opacity-50 mb-0.5">
                Processing Latency
              </span>
              <span className="text-sm font-bold font-mono-code">0.42s</span>
            </div>

            <div className="flex flex-col">
              <span className="font-mono-code text-[9px] uppercase opacity-50 mb-0.5">
                Object Groups
              </span>
              <span className="text-sm font-bold font-mono-code">
                {scan.objectGroups.length} Clusters
              </span>
            </div>

            <div className="flex flex-col">
              <span className="font-mono-code text-[9px] uppercase opacity-50 mb-0.5">
                Atmospheric Shift
              </span>
              <span className="text-sm font-bold font-mono-code text-[#FF5F00]">
                {scan.atmosphericShift}
              </span>
            </div>
          </div>

          <div className="flex items-center gap-3 w-full sm:w-auto justify-end">
            <button
              onClick={exportPlanAsMarkdown}
              className="border border-black bg-white px-5 py-2.5 text-[11px] font-mono-code uppercase tracking-widest font-bold hover:bg-black hover:text-white transition-colors flex items-center gap-2 shadow-[3px_3px_0px_#1A1A1A]"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Export Plan</span>
            </button>

            <button
              onClick={onNewScanClick}
              className="bg-black text-white px-6 py-2.5 text-[11px] font-mono-code uppercase tracking-widest font-bold hover:bg-[#FF5F00] transition-colors shadow-[3px_3px_0px_#1A1A1A] flex items-center gap-2"
            >
              <RefreshCw className="w-3.5 h-3.5" />
              <span>Scan New Room</span>
            </button>
          </div>
        </div>
      </section>
    </div>
  );
};
